using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ProblematicCode : MonoBehaviour
{
    //WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY 
    //    ____________________________________________________________________________                                                                                                                                             //| 
    //   |Room 1                                      |         |            __       |                                                                                                                                            //|   
    //   |                                            |         |           |__|      |                                                                                                                                            //|
    //   |                                            |         |                 _   |                                                                                                                                            //|
    //   |    title.text = Card.Data.DisplayName;     |         | |----|----|    |_|  |                                                                                                                                            //|
    //   |    -----------------------------------     |         | | bo | co |    _|_  |                                                                                                                                           //|
    //   |   |                                    |   |         | |----|----|   |___| |                                                                                                                                            //|
    //   |   |___________________________________ |   |         |_____________________|                                                                                                                                            //|
    //   |____________________________________________|_______________________________|                                                                                                                                            //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|           
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                              //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                             //|
    //                                                                                                                                                                                                                                    
    //WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY WHERE THEY STAY 
}
